### command to install 

In [1]:
pip install numpy

### Import numpy

In [2]:
import numpy as np

### Creating array

In [3]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


## NumPy
*Python Lists vs NumPy Arrays*

---

1. NumPy arrays are faster (optimized in C)
2. NumPy stores data in continuous memory blocks => store data in sequence not in random memory places
3. Uses less memory (optimized storage)
4. Built-in mathematical functions
5. Supports direct vectorized operations

### Performence in terms of Time

In [6]:
import time  

size = 10_000_000

# python list
py_list = list(range(size))  
start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()
print(f"Time taken by python list {end_time - start_time} seconds")

# numpy array
np_arr = np.array(py_list)
start_time = time.time()
#vectorization =>ability to perform maths operation without using loops
sq_arr = np_arr ** 2
end_time = time.time()
print(f"Time taken by Numpy array {end_time - start_time} seconds")

Time taken by python list 9.756366968154907 seconds
Time taken by Numpy array 0.08295774459838867 seconds


### Performence in terms of Storage

In [9]:
import sys  # bridge btw interperter and os and also control and access system parameters & fnx
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes") # it store extra data => type,datatype etc

print(f"python list size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
python list size = 80000000 bytes


## NumPy

So why is Numpy faster?

* Homogeneous Data Types and Contiguous Memory
* Vector Operations & C Implementations
* Reduced Overhead

### Creating Numpy Arrays

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print(type(arr))
print(arr.dtype) #datatype

print("\n")

arr2 = np.array([1,2,3,4,"array"])
print(arr2)
print(type(arr2))
print(arr2.dtype) #datatype

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int64


['1' '2' '3' '4' 'array']
<class 'numpy.ndarray'>
<U21


### Shape => dimensions => no of elements

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr.shape)

(10,)


### 2D Numpy Array

In [19]:
arry_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arry_2D)
print(arry_2D.shape) # 3 rows and 3 cols

print("\n")

arry_2D_02 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arry_2D_02)
print(arry_2D_02.shape) # 4 rows and 3 cols

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## Note about 2D array 
1- Array must be Homogenious => equal size in every row

### Creating Numpy Array from Scratch

In [23]:
arr1 = np.zeros((2,3)) # array with 2 rows , 3 cols and fill with zeroes
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
float64


In [25]:
arr2 = np.ones((3,4))
print(arr2)
print(arr2.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


### change in datatype

In [28]:
arr = np.zeros((3,4), dtype ="int64")
print(arr)
print(arr.shape)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
int64


In [32]:
arr = np.full((3,4),20) # fill with 20
print(arr)
print(arr.shape,"\n")


[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]
(3, 4) 



###  Identity Matrix in NumPy (Mini Notes)

An **Identity Matrix** is a square matrix (equal rows and columns) where all main diagonal elements are **`1`** and all other elements are **`0`**. 

It acts exactly like the number `1` in regular math—multiplying any matrix by an identity matrix results in the original matrix unchanged ($A \times I = A$).



### Output:
##### [[1 0 0]
#####  [0 1 0]
#####  [0 0 1]]

In [33]:
arr = np.eye((3)) # identity metrics => pass only single value
print(arr)
print(arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


### Arrange fnx

In [37]:
arr = np.arange(0,11,2) # start,end,steps => start included , end not included
print(arr)
print(arr.shape)
print("\n")
arr2 = arr = np.arange(10,100,5) # start=10,end = 100 ,steps = 5 => start included , end not included
print(arr)
print(arr.shape)


[ 0  2  4  6  8 10]
(6,)


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)


## 📍 NumPy `np.linspace()` 

`np.linspace()` is used to create an array of **evenly spaced numbers** over a specified mathematical interval. 

The biggest advantage is control: instead of guessing the step size, you simply tell NumPy **how many total elements** you want between your start and end points.

---

### 🛠️ Syntax & Core Parameters

```python
np.linspace(start, stop, num=50)

In [42]:
arr2 = arr = np.linspace(1,100,7) 
print(arr)
print(arr.shape)

[  1.   17.5  34.   50.5  67.   83.5 100. ]
(7,)


### Properties Of Numpy Array

In [52]:
# for 2d

arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr1)
print(arr1.shape)
print(arr1.size) # total elem
print(arr1.dtype) # datatype
print(arr1.ndim) # dimension of array


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2


### Type casting in numpy

In [55]:
# from int to float
arr=np.array([[1,2,3,4],[5,6,7,8],[8,9,0,1]])

float_arry = arr.astype(np.float64)
print(float_arry)
print(float_arry.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [8. 9. 0. 1.]]
float64


### Operations in Numpy

### 1- Reshape

In [60]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape)
print(" \n Array after Reshaping .... \n")
reshaped_arr = arr.reshape(5,2) # reshape() in NumPy is used to change the shape (dimensions) of an array without changing its data.
print(reshaped_arr)
print(reshaped_arr.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
 
 Array after Reshaping .... 

[[1 2]
 [3 4]
 [5 4]
 [5 6]
 [7 8]]
(5, 2)


### 2- flatten array=> 2D to 1D array

In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
flattene_arr = arr.flatten()
print(flattene_arr)
print(flattene_arr.shape)

[1 2 3 4 5 4 5 6 7 8]
(10,)


### 3 - Indexing in array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])
print(arr[4])
print(arr[7])
print(arr[9])

1
5
8
10


### indexing for 2D array

In [3]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])

print(arr[0][0])
print(arr[0][3])
print(arr[1][0])
print(arr[1][4])

1
4
4
8


### Fancy and Boolean Indexing

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])

idx = [0,4,6,8]
print(arr[idx])
# Boolean => indexing based on conditions
print(arr[arr > 5])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[1 5 7 9]
[6 7 8 9]
[2 4 6 8]
[1 3 5 7 9]


### 4 - Slicing 

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9])
# slicing => start,end.not_include , step

print(arr[0:9:2])
print(arr[3:])
print(arr[:5])
print(arr[::3])
print(arr[::-1])

[1 3 5 7 9]
[4 5 6 7 8 9]
[1 2 3 4 5]
[1 4 7]
[9 8 7 6 5 4 3 2 1]


## ✂️ Python List Slicing vs. NumPy Slicing

### ⚡ Core Differences

| Feature | Python Lists | NumPy Arrays |
| :--- | :--- | :--- |
| **Memory** | Creates a **New Copy** | Creates a **View** (Shares memory) |
| **Editing Slice** | Original remains unchanged | Original **gets modified** |
| **2D Syntax** | Chained: `list[0][1:3]` | Comma-separated: `arr[0, 1:3]` |
| **Performance** | Slower (Copies data) | Instantaneous (No data copy) |


In [21]:
# copy VS View
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums,"\n")

# with numpy array
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5] 

[2 3]
[200   3]
[  1 200   3   4   5]


### Common Numpy Data Types

In [28]:
arr = np.array([1,2,3,4,5]) #int
arr2 = np.array([1,2.2,3,4,5]) #float
arr3 = np.array([1,2.2,3,4,5,"prime"]) #string

arr_complex = np.array([3 + 5j])
arr_complex02 = np.array([2 + 3j])

print(arr_complex,arr_complex.dtype)
print(arr_complex + arr_complex02)
print(arr_complex - arr_complex02)

print(arr,arr.dtype)
print(arr2,arr2.dtype)
print(arr3,arr3.dtype)


object_arr = np.array(["prime",{1,2,3,4,5},3.14]) # Object
print(object_arr,object_arr.dtype)

[3.+5.j] complex128
[5.+8.j]
[1.+2.j]
[1 2 3 4 5] int64
[1.  2.2 3.  4.  5. ] float64
['1' '2.2' '3' '4' '5' 'prime'] <U32
['prime' {1, 2, 3, 4, 5} 3.14] object


## 📐 NumPy Axes in Multi-Dimensional Arrays

In NumPy, **dimensions** are referred to as **axes**. The number of axes defines the structure and how you index data within the array.


---

### 🗺️ Axis Breakdown by Dimension

#### 1. 1D Arrays (1 Axis)
* **`axis 0`**: Represents the single linear sequence of elements.
* *Visual:* `[ 1 | 2 | 3 | 4 ]`

#### 2. 2D Arrays (2 Axes)
* **`axis 0`**: Rows (Moving **vertically** downward $\downarrow$)
* **`axis 1`**: Columns (Moving **horizontally** across $\rightarrow$)

#### 3. 3D Arrays (3 Axes)
Think of a 3D array as a stack of multiple 2D grids (layers/matrices).
* **`axis 0`**: Depth / Layers / Sheets (Which 2D grid to look at)
* **`axis 1`**: Rows inside that specific layer ($\downarrow$)
* **`axis 2`**: Columns inside that specific layer ($\rightarrow$)

---

### 🔍 Decoding 3D Indexing: `arr3D[1, 2, 0]`

From the blackboard example, when accessing an element using `arr3D[layer, row, col]`:

1.  **`1` (axis 0)** $\rightarrow$ Jump to **Layer index 1** (the middle grid).
2.  **`2` (axis 1)** $\rightarrow$ Move down to **Row index 2** inside that grid.
3.  **`0` (axis 2)** $\rightarrow$ Isolate **Column index 0** (the first column slot).

In [41]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D,axis = 0) # array,axis
sum_of_row = np.sum(arr2D,axis = 1) # array,axis
print(sum_of_columns)
print(sum_of_row)


print(arr2D[0:2,1:2]) #rows, cols => last not included
print(arr2D[1:3,2:3]) #rows, cols => last not included

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]
[[6]
 [9]]


### For 3D array

In [45]:
# 3D array
arr3D = np.array([[[1,2],[3,4],[5,6]] , [[7,8],[9,10],[11,12]]]) # 2  x 3 x 2 => 2D arrays x rows x cols
print(arr3D)
print(arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
