### command to install 

In [1]:
pip install numpy

### Import numpy

In [2]:
import numpy as np

### Creating array

In [3]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


## NumPy
*Python Lists vs NumPy Arrays*

---

1. NumPy arrays are faster (optimized in C)
2. NumPy stores data in continuous memory blocks => store data in sequence not in random memory places
3. Uses less memory (optimized storage)
4. Built-in mathematical functions
5. Supports direct vectorized operations

### Performence in terms of Time

In [6]:
import time  

size = 10_000_000

# python list
py_list = list(range(size))  
start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()
print(f"Time taken by python list {end_time - start_time} seconds")

# numpy array
np_arr = np.array(py_list)
start_time = time.time()
#vectorization =>ability to perform maths operation without using loops
sq_arr = np_arr ** 2
end_time = time.time()
print(f"Time taken by Numpy array {end_time - start_time} seconds")

Time taken by python list 9.756366968154907 seconds
Time taken by Numpy array 0.08295774459838867 seconds


### Performence in terms of Storage

In [9]:
import sys  # bridge btw interperter and os and also control and access system parameters & fnx
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes") # it store extra data => type,datatype etc

print(f"python list size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
python list size = 80000000 bytes


## NumPy

So why is Numpy faster?

* Homogeneous Data Types and Contiguous Memory
* Vector Operations & C Implementations
* Reduced Overhead

### Creating Numpy Arrays

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print(type(arr))
print(arr.dtype) #datatype

print("\n")

arr2 = np.array([1,2,3,4,"array"])
print(arr2)
print(type(arr2))
print(arr2.dtype) #datatype

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int64


['1' '2' '3' '4' 'array']
<class 'numpy.ndarray'>
<U21


### Shape => dimensions => no of elements

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr.shape)

(10,)


### 2D Numpy Array

In [19]:
arry_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arry_2D)
print(arry_2D.shape) # 3 rows and 3 cols

print("\n")

arry_2D_02 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arry_2D_02)
print(arry_2D_02.shape) # 4 rows and 3 cols

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## Note about 2D array 
1- Array must be Homogenious => equal size in every row

### Creating Numpy Array from Scratch

In [23]:
arr1 = np.zeros((2,3)) # array with 2 rows , 3 cols and fill with zeroes
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
float64


In [25]:
arr2 = np.ones((3,4))
print(arr2)
print(arr2.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


### change in datatype

In [28]:
arr = np.zeros((3,4), dtype ="int64")
print(arr)
print(arr.shape)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
int64


In [32]:
arr = np.full((3,4),20) # fill with 20
print(arr)
print(arr.shape,"\n")


[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]
(3, 4) 



###  Identity Matrix in NumPy (Mini Notes)

An **Identity Matrix** is a square matrix (equal rows and columns) where all main diagonal elements are **`1`** and all other elements are **`0`**. 

It acts exactly like the number `1` in regular math—multiplying any matrix by an identity matrix results in the original matrix unchanged ($A \times I = A$).



### Output:
##### [[1 0 0]
#####  [0 1 0]
#####  [0 0 1]]

In [33]:
arr = np.eye((3)) # identity metrics => pass only single value
print(arr)
print(arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


### Arrange fnx

In [37]:
arr = np.arange(0,11,2) # start,end,steps => start included , end not included
print(arr)
print(arr.shape)
print("\n")
arr2 = arr = np.arange(10,100,5) # start=10,end = 100 ,steps = 5 => start included , end not included
print(arr)
print(arr.shape)


[ 0  2  4  6  8 10]
(6,)


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)


## 📍 NumPy `np.linspace()` 

`np.linspace()` is used to create an array of **evenly spaced numbers** over a specified mathematical interval. 

The biggest advantage is control: instead of guessing the step size, you simply tell NumPy **how many total elements** you want between your start and end points.

---

### 🛠️ Syntax & Core Parameters

```python
np.linspace(start, stop, num=50)

In [42]:
arr2 = arr = np.linspace(1,100,7) 
print(arr)
print(arr.shape)

[  1.   17.5  34.   50.5  67.   83.5 100. ]
(7,)


### Properties Of Numpy Array

In [52]:
# for 2d

arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr1)
print(arr1.shape)
print(arr1.size) # total elem
print(arr1.dtype) # datatype
print(arr1.ndim) # dimension of array


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2


### Type casting in numpy

In [55]:
# from int to float
arr=np.array([[1,2,3,4],[5,6,7,8],[8,9,0,1]])

float_arry = arr.astype(np.float64)
print(float_arry)
print(float_arry.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [8. 9. 0. 1.]]
float64


### Operations in Numpy

### 1- Reshape

In [60]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape)
print(" \n Array after Reshaping .... \n")
reshaped_arr = arr.reshape(5,2) # reshape() in NumPy is used to change the shape (dimensions) of an array without changing its data.
print(reshaped_arr)
print(reshaped_arr.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
 
 Array after Reshaping .... 

[[1 2]
 [3 4]
 [5 4]
 [5 6]
 [7 8]]
(5, 2)
